name: 🐛 Bug report
description: "Provide information about a problem or issue that occurred with the platfrom."
title: "🐛 Bug:"
labels: "🐛 Bug report"
body: 
  - type: markdown
    attributes:
      value: |
        Please fill out this form as best as you can.
  - type: textarea
    id: context
    attributes:
      label: ℹ️ Context
      description: "Include additional information regarding the objective or background of this issue."
      placeholder: 
      value:
  - type: textarea
    id: benefits
    attributes:
      label: "👣 Steps to reproduce"
      description: "Use a numbered list of steps that are needed to reproduce the issue"
      placeholder:  
      value: "1." 
  - type: textarea
    id: outcomes
    attributes:
      label: "🎯 Expected results"
      description: "What was supposed to happen"
      placeholder: 
      value: "1."
  - type: textarea
    id: outcomes
    attributes:
      label: "👀 Actual results"
      description: "What actually happened"
      placeholder: 
      value: "1."
  - type: textarea
    id: resources
    attributes:
      label: "🕵️ Evidence of issue"
      description: "Add logs, session recordings or screenshots"
      placeholder: "You can attach images or log files by clicking this area to highlight it and then dragging files in."
      value:
