name: 🐛 Bug report
description: "Provide information about a problem or issue that occurred with the platfrom."
title: "🐛 Bug:"
labels: "🐛 Bug"
body: 
  - type: markdown
    attributes:
      value: |
        Please fill out this form as best as you can.
  - type: textarea
    id: context
    attributes:
      label: ℹ️ Context
      description: "Include additional information regarding the background of this issue."
      placeholder: 
      value:
 
