name: 🔮 Feature
description: A spike is used to gain the knowledge necessary to reduce the risk of a technical approach, better understand a requirement, or increase the reliability of a story estimate..
title: "FEATURE: "
labels: "🔮 Feature"
body: 
  - type: markdown
    attributes:
      value: |
        Please fill out this form as best as you can.
  - type: textarea
    id: context
    attributes:
      label: ℹ️ User Story
      description: "Include additional information regarding the objective or background of this issue."
      placeholder: 
      value: |
      "As [a user persona],
      I want [to perform this action]
      so that [I can accomplish this goal]."
  - type: input
    id: timebox
    attributes:
      label: ⌛ Timebox
      description: "How much time should be spent on this spike"
      placeholder: 1 day
      value:
  - type: textarea
    id: benefits
    attributes:
      label: "💪 Benefits"
      description: "How will this spike advance the product or our understanding."
      placeholder:  
      value: "1." 
  - type: textarea
    id: outcomes
    attributes:
      label: "🎯 Outcomes"
      description: "What do we want to achieve with this research."
      placeholder: 
      value: "1."
  - type: textarea
    id: resources
    attributes:
      label: "📚 Resources"
      description: "List some related resources eg documentation links, figma designs etc"
      placeholder: "You can attach images or log files by clicking this area to highlight it and then dragging files in."
      value:
