name: 🤖 Tech Task
description: A task represents work that needs to be done.
title: "[🤖 Tech]: "
labels: Tech Task
body:
  - type: markdown
    attributes:
      value: |
        To create a tech task, please fill out all of the required details below.
  - type: textarea
    id: context
    attributes:
      label: ℹ️ Context
      description: Provide some context for this task
      placeholder: 
      value:
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 📋 Acceptance Criteria
      description: "The conditions that must be satisfied for the task to be accepted. These should be numbered."
      placeholder: 
      value: "1." 
    validations:
      required: true
  - type: textarea
    id: technical-guidance
    attributes:
      label: "💡 Technical guidance"
      description: "Proved some technical guidance for completing this task. These should be numbered."
      placeholder: 
      value: "1."
    validations:
      required: false
  - type: textarea
    id: resources
    attributes:
      label: 📚 Resources
      description: List some related resources eg documentation links, figma designs etc
      placeholder: Link to a figma design
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      value:
    validations:
      required: false
  - description: A task represents work that needs to be done.