name: 🌱 User Story
description:  "A user story is an informal, general explanation of a software feature written from the perspective of the end user or customer."
labels: "🌱 Enhancement"
body: 
  - type: markdown
    attributes:
      value: |
        Please fill out this form as best as you can.
  - type: textarea
    id: context
    attributes:
      label: 📖 User Story
      description: "Include additional information regarding the objective or background of this issue."
      placeholder: 
      value: |
        As [a user persona],
        I want [to perform this action]
        so that [I can accomplish this goal].
   