name: 🌱 User Story
description:  "A user story is an informal, general explanation of a software feature written from the perspective of the end user or customer."
title: "User Story: "
labels: "🌱 Enhancement"
body: 
  - type: markdown
    attributes:
      value: |
        Please fill out this form as best as you can.
  - type: textarea
    id: user-story
    attributes:
      label: 📖 User Story
      description: "Include additional information regarding the objective or background of this issue."
      placeholder: 
      value: |
        As [a user persona],
        I want [to perform this action]
        so that [I can accomplish this goal].
  - type: textarea
    id: context
    attributes:
      label: ℹ️ Context
      description: "Include additional information regarding the objective or background of this issue."
      placeholder: 
      value:
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "📋 Acceptance Criteria"
      description: "These are the conditions that must be satisfied for the task to be accepted. These should be numbered."
      placeholder: 
      value: "1." 
  - type: textarea
    id: technical-guidance
    attributes:
      label: "💡 Technical guidance"
      description: "Proved some technical guidance for completing this task. These should be numbered."
      placeholder: 
      value: "1."
  - type: textarea
    id: resources
    attributes:
      label: "📚 Resources"
      description: "List some related resources eg documentation links, figma designs etc"
      placeholder: "You can attach images or log files by clicking this area to highlight it and then dragging files in."
      value: